/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TalkImport } from './routes/talk'
import { Route as PortfolioImport } from './routes/portfolio'
import { Route as MlrugImport } from './routes/mlrug'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TalkRoute = TalkImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioRoute = PortfolioImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRoute,
} as any)

const MlrugRoute = MlrugImport.update({
  id: '/mlrug',
  path: '/mlrug',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/mlrug': {
      id: '/mlrug'
      path: '/mlrug'
      fullPath: '/mlrug'
      preLoaderRoute: typeof MlrugImport
      parentRoute: typeof rootRoute
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioImport
      parentRoute: typeof rootRoute
    }
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mlrug': typeof MlrugRoute
  '/portfolio': typeof PortfolioRoute
  '/talk': typeof TalkRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mlrug': typeof MlrugRoute
  '/portfolio': typeof PortfolioRoute
  '/talk': typeof TalkRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mlrug': typeof MlrugRoute
  '/portfolio': typeof PortfolioRoute
  '/talk': typeof TalkRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/mlrug' | '/portfolio' | '/talk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/mlrug' | '/portfolio' | '/talk'
  id: '__root__' | '/' | '/about' | '/mlrug' | '/portfolio' | '/talk'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MlrugRoute: typeof MlrugRoute
  PortfolioRoute: typeof PortfolioRoute
  TalkRoute: typeof TalkRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MlrugRoute: MlrugRoute,
  PortfolioRoute: PortfolioRoute,
  TalkRoute: TalkRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/mlrug",
        "/portfolio",
        "/talk"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/mlrug": {
      "filePath": "mlrug.tsx"
    },
    "/portfolio": {
      "filePath": "portfolio.tsx"
    },
    "/talk": {
      "filePath": "talk.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
